name: 部署文档

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 设置 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.18.2

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: 安装依赖
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run docs:build
          > docs/.vuepress/dist/.nojekyll
          echo "blog.honahec.cc" > docs/.vuepress/dist/CNAME
          echo ${{ secrets.INDEXNOW_KEY }} > docs/.vuepress/dist/${{ secrets.INDEXNOW_KEY }}.txt

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/.vuepress/dist

      # 等待 GitHub Pages 更新
      - name: Wait for GitHub Pages to update
        run: sleep 60

      - name: submit-to-bing
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: "https://blog.honahec.cc/sitemap.xml"
          endpoint: "www.bing.com"
          since: 30
          since-unit: "day"
          key: ${{ secrets.INDEXNOW_KEY }}
          key-location: ${{ secrets.INDEXNOW_KEY_LOCATION }}

      # 刷新 DogeCloud CDN 缓存
      - name: Refresh DogeCloud CDN
        env:
          DOGE_ACCESS_KEY: ${{ secrets.DOGE_ACCESS_KEY }}
          DOGE_SECRET_KEY: ${{ secrets.DOGE_SECRET_KEY }}
        run: |
          API_PATH="/cdn/refresh/add.json"
          BODY='rtype=path&urls=["https://blog.honahec.cc/"]'
          STRING_TO_SIGN=$'/cdn/refresh/add.json\n'"$BODY"
          SIGN=$(printf "%b" "$STRING_TO_SIGN" | openssl dgst -sha1 -hmac "$DOGE_SECRET_KEY" | awk '{print $NF}')
          echo "Calculated SIGN: $SIGN"

          curl -s -X POST "https://api.dogecloud.com${API_PATH}" \
            -H "Authorization: TOKEN ${DOGE_ACCESS_KEY}:${SIGN}" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "$BODY" \
            -o response.json

          echo "DogeCloud Response:"
          cat response.json

